name: Set OpenAI Key

on:
  push:
    branches:
      - main

jobs:
  set_openai_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variable from secret
        run: echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV

      - name: Print Environment Variables Before Streamlit
        run: env
