name: Set OpenAI Key

on:
  push:
    branches:
      - main

jobs:
  set-key:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable from secret
        run: echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV
