name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Environment Variables
        run: env

      - name: Set environment variable from secret
        run: echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Deploy Streamlit app
        run: |
          streamlit run your_app.py
